-- Init script eseguito da gvenzl/oracle-free sul PDB FREEPDB1.
-- I file in /container-entrypoint-initdb.d/ vengono eseguiti come SYSTEM:
-- ci colleghiamo esplicitamente come APP_USER per popolare il suo schema.

CONNECT testuser/testpassword@//localhost:1521/FREEPDB1

CREATE TABLE characters (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    universe        VARCHAR2(100),
    first_appearance DATE,
    creator         VARCHAR2(100),
    gender          VARCHAR2(10),
    species         VARCHAR2(50),
    alignment       VARCHAR2(20)
);

INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brett Diaz', 'DC', DATE '1953-10-17', 'Debra Jones', 'Female', 'Alien', 'Good');
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Daniel Murphy', 'DC', DATE '1951-12-22', 'Andrew Johnson', 'Female', 'Robot', 'Good');
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Heidi Carrillo', 'Image', DATE '1977-03-08', 'Jade Strong', 'Male', 'Animal', 'Evil');
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Margaret Sloan', 'Marvel', DATE '2020-10-11', 'Carla Fox', 'Female', 'Alien', 'Evil');

CREATE INDEX idx_characters_universe ON characters (universe);

CREATE TABLE users (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100),
    email   VARCHAR2(100)
);

INSERT INTO users (name, email) VALUES ('John Doe', 'john.doe@example.com');
INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane.smith@example.com');

CREATE OR REPLACE VIEW character_details AS
    SELECT id, name, universe, first_appearance
    FROM characters;

CREATE MATERIALIZED VIEW character_details_mv AS
    SELECT id, name, universe
    FROM characters;

CREATE SEQUENCE seq_demo START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE copy_characters AS
BEGIN
    INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment)
    SELECT name || ' (copy)', universe, first_appearance, creator, gender, species, alignment
    FROM characters
    WHERE ROWNUM <= 1;
END;
/

COMMIT;
