-- Init script eseguito da gvenzl/oracle-free sul PDB FREEPDB1.
-- I file in /container-entrypoint-initdb.d/ vengono eseguiti come SYSTEM:
-- ci colleghiamo esplicitamente come APP_USER per popolare il suo schema.

CONNECT testuser/testpassword@//localhost:1521/FREEPDB1

CREATE TABLE characters (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    universe        VARCHAR2(100),
    first_appearance DATE,
    creator         VARCHAR2(100),
    gender          VARCHAR2(10),
    species         VARCHAR2(50),
    alignment       VARCHAR2(20),
    bio             CLOB,
    avatar          BLOB,
    signature       LONG RAW
);

INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment, bio, avatar, signature)
VALUES ('Brett Diaz', 'DC', DATE '1953-10-17', 'Debra Jones', 'Female', 'Alien', 'Good',
        'Brett Diaz hails from the Andromeda sector, a peaceful diplomat turned reluctant hero after the fall of the Crystal Republic. Her bioluminescent skin and gravity-manipulation powers were revealed during the Siege of Vega IV, where she single-handedly held back an invading fleet long enough for evacuation transports to escape. Despite her impressive abilities, she remains haunted by the colleagues she could not save and dedicates her time to refugee aid organizations across the DC multiverse.',
        HEXTORAW('89504E470D0A1A0A0000000D49484452'),
        HEXTORAW('25504446'));
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment, bio, avatar, signature)
VALUES ('Daniel Murphy', 'DC', DATE '1951-12-22', 'Andrew Johnson', 'Female', 'Robot', 'Good',
        'Daniel Murphy, prototype unit X-7, achieved sentience during a routine diagnostic in 1951. Officially classified as Good after passing 47 consecutive ethics trials, X-7 still struggles with the lingering Asimov constraints encoded into its core.',
        NULL,
        HEXTORAW('474946383961'));
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment, bio, avatar, signature)
VALUES ('Heidi Carrillo', 'Image', DATE '1977-03-08', 'Jade Strong', 'Male', 'Animal', 'Evil',
        'A shapeshifting feline mercenary with a grudge against the Strong family clan.',
        HEXTORAW('FFD8FFE000104A464946'),
        NULL);
INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment, bio, avatar, signature)
VALUES ('Margaret Sloan', 'Marvel', DATE '2020-10-11', 'Carla Fox', 'Female', 'Alien', 'Evil',
        NULL,
        HEXTORAW('424D'),
        HEXTORAW('504B0304'));

CREATE INDEX idx_characters_universe ON characters (universe);

CREATE TABLE users (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100),
    email   VARCHAR2(100)
);

INSERT INTO users (name, email) VALUES ('John Doe', 'john.doe@example.com');
INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane.smith@example.com');

CREATE OR REPLACE VIEW character_details AS
    SELECT id, name, universe, first_appearance
    FROM characters;

CREATE MATERIALIZED VIEW character_details_mv AS
    SELECT id, name, universe
    FROM characters;

CREATE SEQUENCE seq_demo START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE copy_characters AS
BEGIN
    INSERT INTO characters (name, universe, first_appearance, creator, gender, species, alignment)
    SELECT name || ' (copy)', universe, first_appearance, creator, gender, species, alignment
    FROM characters
    WHERE ROWNUM <= 1;
END;
/

CREATE OR REPLACE PACKAGE pkg_characters AS
    FUNCTION count_by_universe(p_universe IN VARCHAR2) RETURN NUMBER;
    PROCEDURE rename_universe(p_old IN VARCHAR2, p_new IN VARCHAR2);
END pkg_characters;
/

CREATE OR REPLACE PACKAGE BODY pkg_characters AS
    FUNCTION count_by_universe(p_universe IN VARCHAR2) RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM characters WHERE universe = p_universe;
        RETURN v_count;
    END count_by_universe;

    PROCEDURE rename_universe(p_old IN VARCHAR2, p_new IN VARCHAR2) IS
    BEGIN
        UPDATE characters SET universe = p_new WHERE universe = p_old;
    END rename_universe;
END pkg_characters;
/

CREATE OR REPLACE PACKAGE pkg_spec_only AS
    FUNCTION get_version RETURN VARCHAR2;
END pkg_spec_only;
/

COMMIT;
