
connections:
- name: localhost
  type: MongoDB
  connection_uri: mongodb://localhost:27017/
- name: "Localhost"
  type: PostgreSQL
  connection_uri: postgresql://testuser:testpassword@localhost:5432/testdb
- name: "Localhost"
  type: Hive/Kyuubi
  host: localhost
  port: 10009
