
connections:
- name: localhost
  type: MongoDB
  connectionURI: mongodb://localhost:27017/
- name: "Localhost"
  type: PostgreSQL
  connectionURI: postgresql://testuser:testpassword@localhost:5432/postgres
- name: "Localhost"
  type: Hive/Kyuubi
  host: localhost
  port: 10009
