
connections:
- name: localhost
  type: MongoDB
  connectionURI: mongodb://localhost:27017/
- name: Bacco
  type: MongoDB
  connectionURI: mongodb://10.64.8.50:27017/
- name: "Bacco prod"
  type: MongoDB
  connectionURI: mongodb://mongouser:mongouser01@10.65.5.220:27017/admin?	retryWrites=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
  user: mongouser
  password: mongouser01
- name: "Localhost"
  type: PostgreSQL
  connectionURI: postgresql://testuser:testpassword@localhost:5432/postgres
- name: "peng-uat"
  type: PostgreSQL
  connectionURI: postgresql://postgres:!ObjectWay2024@postgresql.operation.novobanco-uat.objectway.com:5432/nb_perf

