
connections:
- name: localhost
  type: MongoDB
  connectionURI: mongodb://localhost:27017/
- name: newconnection
  type: MongoDB
  connectionURI: mongodb://localhost:27017/
- name: Bacco
  type: MongoDB
  connectionURI: mongodb://10.64.8.50:27017/
    