version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - ./dbinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  pgsql:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
