CREATE SCHEMA comics;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100)
);


INSERT INTO users (name, email) VALUES ('John Doe', 'john.doe@example.com');
INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane.smith@example.com');
INSERT INTO users (name, email) VALUES ('Alice Johnson', 'alice.johnson@example.com');
INSERT INTO users (name, email) VALUES ('Bob Brown', 'bob.brown@example.com');


CREATE TABLE comics.characters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    universe VARCHAR(100),
    first_appearance DATE,
    creator VARCHAR(100),
    gender VARCHAR(10),
    species VARCHAR(50),
    alignment VARCHAR(20)
);
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Hicks', 'Image', '1997-10-22', 'Savannah Goodwin', 'Female', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Scott Meyer', 'Image', '1987-11-15', 'Tracy Wilkinson', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Davis', 'Image', '1980-06-26', 'Gloria Morales', 'Other', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mark Valdez', 'Dark Horse', '1987-05-27', 'Walter Ross', 'Other', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Heidi Carrillo', 'Image', '1977-03-08', 'Jade Strong', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sandra Mcfarland', 'Image', '1960-02-03', 'Daniel Moreno', 'Other', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brett Diaz', 'DC', '1953-10-17', 'Debra Jones', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jeffrey Peterson', 'Dark Horse', '1980-12-11', 'Daniel Brown', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christina Fields', 'Dark Horse', '1953-02-24', 'Elizabeth Bishop', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Alexandria Robinson', 'Image', '1947-08-06', 'Joseph Mckee Jr.', 'Male', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Daniel Murphy', 'DC', '1951-12-22', 'Andrew Johnson', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jeffrey Sherman', 'Dark Horse', '1980-11-03', 'Audrey Yang', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Benjamin Lynn', 'Image', '1984-06-09', 'Sabrina Moore', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Adam Lane', 'Dark Horse', '1947-10-14', 'Danielle Villanueva', 'Other', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sean Jones', 'Dark Horse', '1958-04-16', 'Sean Evans', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kevin Howard', 'DC', '1989-02-18', 'Ricky Morrison', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Megan Shields', 'Dark Horse', '1961-01-08', 'Lisa Holt', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Margaret Sloan', 'Marvel', '2020-10-11', 'Carla Fox', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Cheryl Harvey', 'Manga', '2013-01-13', 'Glen Schultz', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Yvonne Franco', 'DC', '1976-05-27', 'Mark Rocha', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Miranda Williams', 'DC', '2019-08-24', 'Rhonda Ramirez', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Katrina Smith', 'Marvel', '2024-06-04', 'Erin Andrews', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Amy Ward', 'Dark Horse', '1968-07-24', 'Linda Swanson', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Carol Porter', 'DC', '1963-04-11', 'Michael Fisher', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michelle Anderson', 'Dark Horse', '2002-12-31', 'Melissa Downs', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mary Walter', 'Marvel', '1980-03-20', 'Justin Zimmerman', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Reginald Galvan', 'Dark Horse', '2001-01-09', 'Jorge Watkins', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dennis Patterson', 'Image', '2008-06-09', 'Travis Allen', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sherry Daniels', 'Dark Horse', '1956-10-18', 'Alyssa Cooke', 'Male', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dale Peterson', 'DC', '1979-09-21', 'Jeffrey Skinner', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Teresa Stewart', 'DC', '1988-11-05', 'Gregory Williams', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Shannon Gates', 'Image', '2018-10-15', 'Amy Washington', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kevin Brooks', 'DC', '2020-04-07', 'Melissa Walker', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Hernandez', 'Marvel', '2008-08-26', 'Jessica Brown', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Karina Richardson', 'Marvel', '1966-09-03', 'Heather Fox PhD', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Robert King', 'Dark Horse', '1970-01-01', 'James Nelson', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Karen Gross', 'Dark Horse', '1966-04-08', 'Allison Walls', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rick Jackson', 'Image', '2018-10-04', 'Benjamin Patterson', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Heather Miller', 'Image', '1948-10-20', 'Joseph Obrien', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Roy Silva', 'DC', '1977-10-04', 'Danielle Pitts', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Diana Clark MD', 'Marvel', '1957-04-05', 'Maria Ford', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joshua Jones', 'Manga', '1996-09-04', 'Mr. William Daniels', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Eric Becker', 'Manga', '2009-01-04', 'Trevor Morris', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Robert Woods', 'DC', '2018-07-06', 'Kim Mcgee', 'Female', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Elizabeth Stevenson', 'DC', '1954-06-25', 'Michael Harris', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Garrett Mahoney', 'Image', '1966-06-28', 'Gina Klein', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jason Woods', 'Image', '1948-03-12', 'Miguel Mitchell', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joe Bush', 'Dark Horse', '1976-05-13', 'James Johnson', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('James Shaw', 'DC', '2004-06-14', 'Eric Thomas', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Laurie Adams', 'Image', '1989-03-26', 'Shawn Smith', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paula Phillips', 'Image', '1951-05-21', 'Megan Thomas', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Patricia Williams', 'DC', '1994-09-13', 'John Lopez', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joshua Garcia', 'Marvel', '1949-12-09', 'Michelle Mcconnell', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Natalie Dominguez', 'Image', '1997-05-03', 'Dana Rhodes', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rachel Jenkins', 'DC', '1952-05-14', 'Lawrence Smith', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christina Wood', 'DC', '1958-09-05', 'Robert Wilson', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paula Valenzuela', 'Image', '1947-03-05', 'Joshua Snyder', 'Other', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Nicholas Wright', 'Manga', '1972-07-26', 'Michael Beltran', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christine Medina', 'Manga', '1950-06-30', 'Michael Moss', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kayla Foster', 'DC', '2005-07-02', 'Ann Garcia', 'Female', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Matthew Chavez', 'Dark Horse', '2021-07-21', 'Charles Cowan', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kathleen Montgomery', 'Marvel', '2010-01-21', 'Lacey Adams', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Douglas Holmes', 'DC', '2014-03-17', 'Teresa Prince', 'Female', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Phillip Woods', 'Marvel', '1967-12-27', 'Lee Crawford', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dawn Allen', 'Manga', '1955-12-28', 'Nicholas Wise', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paul Herrera', 'Manga', '2013-05-30', 'Jennifer Mendez', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('William Moreno', 'Marvel', '1968-01-18', 'Vanessa Smith', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ashley Allen', 'Manga', '1989-04-10', 'Robert Molina', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Grace Reeves', 'Manga', '1979-05-09', 'Beth Hall', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Matthew Maxwell', 'Manga', '1976-04-16', 'Ashley Kane', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Taylor Palmer', 'Image', '2016-01-07', 'Timothy Smith', 'Female', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Maria Boyle', 'DC', '1969-01-12', 'Sarah Kennedy', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Melanie Parker', 'Manga', '1984-02-13', 'Kimberly Young', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jennifer Miller', 'Manga', '1981-05-04', 'Lindsay Espinoza', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Williams', 'Image', '1978-07-26', 'Jose Mueller', 'Other', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Austin Tanner', 'Dark Horse', '2016-11-23', 'Ronald Garcia', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('John Brown', 'Image', '2022-01-23', 'Thomas Fisher', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Stephanie Bailey', 'Manga', '1978-01-28', 'Melissa Figueroa', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Debra Booth', 'Dark Horse', '1962-02-17', 'Jasmine Williams', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jason Anderson', 'Dark Horse', '1978-09-25', 'Nicholas Moore', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Patrick Jones', 'Image', '2020-04-21', 'Mario Jacobson', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paula Smith', 'Dark Horse', '1950-12-11', 'Corey Harris', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Lisa Watkins', 'Manga', '1949-08-03', 'Daniel Johnston', 'Other', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Samantha Crawford', 'Marvel', '1982-06-22', 'Elizabeth Harper', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Donald Lee', 'Marvel', '1994-06-04', 'William Anderson', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paula Gonzalez', 'Image', '2004-06-10', 'Robert Ayala PhD', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christina Boyd', 'Dark Horse', '2015-06-11', 'Craig Flowers', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sherri Garcia', 'DC', '1967-09-07', 'Michael Colon', 'Female', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Carol Terry', 'Manga', '2017-09-07', 'Ashley King', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Julie Floyd', 'Manga', '1973-01-09', 'Julian Gardner', 'Female', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Paul Mitchell', 'DC', '1971-02-28', 'Megan Williams', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jessica Jones', 'Dark Horse', '1960-12-28', 'Kylie Fisher', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Donald Green', 'Dark Horse', '1961-03-12', 'Taylor Hill DVM', 'Female', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Theresa Jimenez', 'Image', '1954-11-26', 'Jeffery Patel', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joshua Buchanan', 'Manga', '1973-05-15', 'Stacy Chandler', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Thompson', 'Marvel', '2009-12-20', 'Brian Cannon', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Stevenson', 'Manga', '1946-11-19', 'Bridget Johnson', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Gina Wright', 'Marvel', '1999-03-10', 'Ryan Rodriguez', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mary Clements', 'Dark Horse', '1981-12-09', 'Zachary Ramirez', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Margaret Atkinson', 'Marvel', '2000-03-04', 'Jennifer Rowe', 'Male', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('James Perry', 'DC', '1994-09-01', 'Devin Williams', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rebecca Mcgee', 'Dark Horse', '1998-03-25', 'Michael Lopez', 'Male', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('David Dean', 'Marvel', '1952-09-03', 'Kevin Gilbert', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jeffrey Fernandez', 'Marvel', '2011-10-20', 'Michael Stewart', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Shea', 'Dark Horse', '1975-10-22', 'Victoria Robles', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Andrew Dixon', 'Manga', '1947-10-29', 'Melissa Graham', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sean Alvarez', 'Image', '2001-07-01', 'Nicole Wilson', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jeffrey Valdez', 'Image', '1963-09-11', 'Brittany Chavez', 'Male', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jesse Hamilton', 'DC', '1988-12-25', 'Kyle Ortega', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Taylor Weiss', 'Manga', '1984-05-04', 'Richard Gordon MD', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Alexandra Moore DDS', 'Image', '1990-03-23', 'Charles Shaw', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Barbara Li', 'Manga', '2016-10-17', 'Rebecca Collins', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Austin Ball', 'Image', '1983-03-10', 'Stacey Clayton', 'Other', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Katherine Finley', 'Dark Horse', '1985-02-13', 'Arthur Hickman', 'Other', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rebecca Pennington', 'DC', '1981-07-16', 'Carolyn Houston', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ryan Duarte', 'Image', '1966-04-01', 'Taylor Scott', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('James Nelson', 'Manga', '1992-09-15', 'Jeremy Jones', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Anthony Gonzalez', 'Image', '2002-02-08', 'Madison Gonzales', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Duane Allen', 'DC', '1946-01-14', 'Jill Taylor', 'Other', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Emily Stuart', 'Image', '1975-08-29', 'Nicole Rivera', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michelle Moore', 'Marvel', '2016-07-26', 'Paula Gonzales', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brian Blackburn', 'Dark Horse', '2007-11-16', 'Ashley Curtis', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mariah Perez', 'Manga', '1976-06-12', 'Phillip Crane', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Angela Horton', 'Marvel', '2012-02-02', 'Jeremiah Rodriguez', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('David Lane', 'DC', '1953-05-31', 'Sherry Collier', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Bush', 'Marvel', '1987-06-12', 'Suzanne Richards', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Robin Meyer', 'Marvel', '2000-09-09', 'Joshua Edwards', 'Female', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Susan Owen', 'Marvel', '1962-02-14', 'Bruce Glover', 'Other', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Denise Hampton', 'Marvel', '1986-06-01', 'John Brown', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jonathan Avila', 'Dark Horse', '2000-03-23', 'Christopher Trevino', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Shelly Franklin', 'Marvel', '2003-10-07', 'Jennifer Rowland', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tyler Richard', 'DC', '2012-06-08', 'Brandon Chase', 'Other', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Nathan Lindsey', 'DC', '1949-02-05', 'Brittany Whitehead', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Carmen Fry', 'Dark Horse', '1981-03-05', 'Connie Edwards', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Bernard Collier', 'Marvel', '1991-02-01', 'John Rivera', 'Female', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brian Hill DDS', 'Dark Horse', '1997-07-30', 'Thomas Ortega', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Shawn Boyd', 'Image', '2008-10-26', 'Anthony Black', 'Female', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tyler Haas', 'Manga', '2022-01-03', 'Juan King', 'Other', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Erin Hebert', 'DC', '1972-11-11', 'Susan Adams', 'Other', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Bianca Shah', 'Image', '1952-07-26', 'Kathy Dillon', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Hannah Beck', 'Image', '1964-05-05', 'Joel Coleman', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Pugh', 'Image', '2022-06-29', 'April Miller', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kevin Thomas', 'Marvel', '1987-09-24', 'Chad Cain', 'Other', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joe Wright', 'Marvel', '1995-01-31', 'Jill Smith', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jennifer Anderson', 'Marvel', '1974-07-15', 'Philip Perez', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Larry Saunders', 'Marvel', '1958-10-29', 'Aaron Vaughan', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Anna Martinez', 'DC', '1976-09-04', 'Paul Thomas', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Austin Lee', 'Marvel', '1989-11-26', 'Brian Meyers', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dustin Myers', 'Manga', '1995-12-06', 'Lisa Johnson', 'Female', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Douglas Cook', 'DC', '2009-06-01', 'Brandon Villegas', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kimberly Rodriguez', 'Marvel', '1946-09-19', 'Allison Munoz', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Linda Perry', 'Dark Horse', '2015-08-06', 'Maria Frederick', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('David Gonzales', 'DC', '1995-10-09', 'Lee Bryant', 'Male', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kathryn Martin', 'DC', '2023-12-29', 'Katherine Wilkerson', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dylan Butler', 'Manga', '1975-11-06', 'Mary Mckenzie', 'Male', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Powers', 'Manga', '2015-10-29', 'Jason Barnett', 'Other', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Heather Trevino', 'Dark Horse', '1992-03-04', 'William Leonard', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Erica Sheppard', 'Marvel', '1961-01-12', 'Maureen Henry', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Barbara Moore', 'Dark Horse', '1954-01-17', 'Heidi Harris', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jennifer Hahn', 'Image', '1974-06-11', 'William Camacho', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Laura Chase', 'Image', '2003-11-16', 'Sheila Mathis', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Allison Bailey', 'Manga', '1988-06-11', 'Alan Mosley', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ruth Perez', 'Manga', '1979-09-07', 'Jamie Harris', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Donald Saunders', 'Manga', '2001-08-22', 'Caleb Donaldson', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jennifer Martin', 'Dark Horse', '2014-09-20', 'Diane Olson', 'Other', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mrs. Sandra Smith', 'Dark Horse', '1948-09-14', 'Matthew Clay', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tina Huff', 'Manga', '2017-02-05', 'Michael Blair', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kristin Ware', 'DC', '1983-09-03', 'Anthony Murray', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Briana Roth', 'Dark Horse', '1952-01-07', 'Mark Gonzalez', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mary Walker', 'Image', '2003-08-12', 'Dennis Garrett', 'Male', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Thomas Jordan', 'Dark Horse', '2012-02-15', 'Stacy Davis', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brenda Miller', 'Manga', '1950-09-28', 'Kiara Saunders', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ryan Ross', 'Image', '2019-06-20', 'Joseph Hughes', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Gregory Francis', 'Dark Horse', '1997-12-19', 'Lucas Ponce', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kimberly Bennett', 'Marvel', '2008-11-17', 'Laura Joseph', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Huang', 'DC', '2018-08-23', 'Melissa Mcgee', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jason Huff', 'Dark Horse', '1993-10-13', 'Valerie Adams', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jason Smith', 'Marvel', '1990-02-04', 'Colleen Jones', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Danielle Pacheco', 'Dark Horse', '1946-04-28', 'Steven Rice Jr.', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Amy Branch', 'Image', '1957-01-30', 'Erika Butler', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Cynthia Rios', 'Marvel', '1966-10-17', 'Wyatt Day', 'Other', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Stephen Gordon', 'Marvel', '1964-12-27', 'Erika Ward', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('John Raymond', 'Marvel', '1958-02-20', 'Michelle Carroll', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Phillip Walker', 'DC', '1972-01-22', 'Sierra Richards', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Melanie Castro', 'Dark Horse', '1986-12-15', 'Nancy Combs', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Angela Contreras', 'Manga', '1955-08-07', 'Daniel Stephens', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Gilbert Ward', 'Image', '1946-06-17', 'Joseph Goodman', 'Female', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sharon Dunn', 'Marvel', '1995-10-27', 'Angela Howard', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Todd Allison', 'Dark Horse', '1999-08-04', 'Cheyenne Mills', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joel Reese', 'Manga', '2015-02-21', 'Katelyn Nichols', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Benjamin', 'DC', '1974-01-20', 'Jason Mcpherson', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joshua Peterson', 'Dark Horse', '1956-02-15', 'Jamie Martin', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tasha Francis', 'Manga', '1957-07-02', 'Paula Reed', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Marks', 'Image', '1953-12-18', 'Mark Sanchez', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christopher Jones', 'Manga', '1970-12-21', 'Timothy Myers', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rachel Rodriguez', 'Manga', '1960-08-23', 'Tonya Jenkins', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Molly Rodriguez', 'Image', '1967-11-14', 'Patricia Briggs', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tyrone Davis', 'Image', '1999-07-11', 'Gregory Webb', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Yvonne Henderson', 'Manga', '1954-12-29', 'Brittany Wong', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Diana Smith', 'DC', '2012-07-16', 'Kenneth Sherman', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Richard Armstrong', 'Dark Horse', '2017-04-13', 'Annette Martin', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Thomas Russell', 'DC', '1952-11-16', 'Jeffrey Ramos', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jeremy Moyer', 'DC', '1993-10-15', 'Chelsea Cook', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dr. Charles Miller', 'Dark Horse', '1984-10-28', 'Robert Larson', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brian Johnson', 'Dark Horse', '1978-11-26', 'Jessica Wilkerson', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joseph Flores', 'Manga', '1990-06-03', 'Curtis Dawson', 'Female', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jessica Jones', 'DC', '2012-03-22', 'Miranda Hendricks', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('William Castillo', 'Dark Horse', '2000-05-24', 'Tracey Pearson', 'Other', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Dawson', 'Dark Horse', '2015-06-29', 'Amber Murray', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tina Ashley', 'Manga', '2014-04-05', 'Jessica Brown', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Robert Miller', 'DC', '1954-12-08', 'Courtney Mitchell', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Briana West', 'Manga', '1994-11-16', 'Lisa Berry', 'Female', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tara Holland', 'Manga', '2003-07-08', 'Carla Taylor', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Christina Luna', 'Marvel', '1996-03-10', 'Karen Lopez', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jason Martinez', 'Dark Horse', '1956-05-03', 'James Green', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Matthew Proctor', 'Dark Horse', '1947-07-19', 'William Oconnell', 'Other', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Alexander Chambers', 'Image', '2016-05-09', 'Shelby Owens', 'Female', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Steve Garcia', 'DC', '1947-03-15', 'Mrs. Meghan Lawrence', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('John Garcia', 'Dark Horse', '1996-04-02', 'Mr. Donald Grant MD', 'Other', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ryan Howard', 'Image', '1978-09-13', 'Chad Kelly', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Amber Bowers', 'Manga', '1987-03-24', 'Katherine Baxter', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Frederick Smith', 'Manga', '1985-09-15', 'Theodore Moore', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Deanna Espinoza', 'Manga', '1973-03-05', 'Raymond Strong', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jonathan Johns', 'Marvel', '1955-11-02', 'Danielle Ross', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mallory Bright', 'Image', '2020-02-25', 'Daniel Walsh', 'Female', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brian Burke', 'Manga', '1946-04-03', 'Mandy Barber', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Morrow', 'Image', '1976-06-24', 'Robin Mitchell', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Nicole Bishop', 'DC', '1964-01-19', 'Caleb Davis', 'Female', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Larry Crosby', 'Image', '1959-10-24', 'Aaron Sanchez', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sheila Thompson', 'Dark Horse', '2018-08-09', 'Benjamin Torres', 'Female', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Diana Peterson', 'DC', '1989-07-23', 'Steven Thompson', 'Other', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Jasmin Mccarty', 'Marvel', '1980-05-30', 'Bobby Caldwell', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Lisa Smith', 'Dark Horse', '2004-04-12', 'John Mcclure', 'Other', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brenda Moreno', 'Image', '1965-07-26', 'Natalie Nelson', 'Other', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Joseph Morrow', 'Image', '2017-09-08', 'Daniel Dixon', 'Female', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sherry Ferguson', 'Image', '1951-07-27', 'Jasmine Roy', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Brian Townsend', 'Manga', '1974-05-04', 'Joshua Blackburn', 'Other', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Taylor Bell', 'DC', '1949-11-09', 'Ricardo Davis', 'Other', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Todd King', 'Dark Horse', '2005-04-13', 'David Gallegos', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Peggy Norman', 'DC', '1948-08-29', 'Fred Johnson', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rebecca May', 'Manga', '1959-05-15', 'Katie Reed', 'Male', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Courtney Trujillo', 'Image', '1993-05-28', 'Terry Klein', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('John Bullock', 'DC', '1962-06-21', 'Brittany Joyce', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ricardo Howard', 'DC', '1988-07-25', 'Kaitlyn Lloyd', 'Other', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('James Evans', 'Dark Horse', '2006-12-31', 'Matthew Garner', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('April Hull', 'Image', '2008-07-13', 'Rebecca Robinson DDS', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Sandra Robinson', 'Dark Horse', '2008-02-13', 'Joshua Williams', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Darius Mitchell', 'Dark Horse', '1977-05-01', 'Valerie Nelson', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ryan Campbell', 'Manga', '1992-01-29', 'Tina Fischer', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mario Shaw', 'Marvel', '2018-01-10', 'Paula Schmidt', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Adam Lloyd', 'DC', '1979-01-13', 'Steven Valdez', 'Male', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michelle Perez DDS', 'Manga', '1995-10-08', 'Beth Parker', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Travis Blackburn', 'Marvel', '2016-08-27', 'Benjamin Morales', 'Male', 'Robot', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ann Davis', 'Image', '2020-02-19', 'Rebecca Mitchell', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Scott Ferguson', 'Dark Horse', '1982-02-14', 'Amber Smith DVM', 'Male', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Daniel Ferguson', 'Manga', '1998-06-15', 'Margaret Boyd', 'Female', 'Mutant', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Eduardo Lane', 'Manga', '2009-08-13', 'David Smith', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dillon Wiggins', 'Marvel', '1957-11-22', 'Holly Estrada', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Troy Jefferson', 'Marvel', '1988-06-11', 'Emily Morales', 'Male', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Abigail Cunningham', 'Manga', '1994-07-29', 'Felicia Hall', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Michael Saunders', 'Marvel', '1992-09-05', 'Nancy Hayden', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Mia Smith', 'Manga', '2008-09-10', 'David Travis', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Suzanne Hartman', 'Marvel', '1987-08-18', 'Casey Chaney', 'Female', 'Alien', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Robert Keller', 'Manga', '1998-03-03', 'John Sanchez', 'Male', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Phillip Lynch', 'Marvel', '1951-11-29', 'Kelly Patel', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Peter Cummings', 'Manga', '1945-03-07', 'Elizabeth Hicks', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Elizabeth Soto', 'Manga', '2021-09-17', 'Jacqueline Chavez', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Alexander Peterson', 'Image', '1988-12-08', 'Heather Mitchell', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Erik Short', 'DC', '2014-06-09', 'Christopher Herrera', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Kristen Rodriguez', 'Dark Horse', '2012-10-02', 'Andrew Thomas', 'Male', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Cristian Richardson', 'Marvel', '1959-11-28', 'Mrs. Katherine Vega', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Alison Holloway', 'DC', '2020-09-10', 'Matthew Patterson', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Marcus Collins', 'Image', '1959-12-01', 'John Johnson', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Karen Wells', 'DC', '1955-10-12', 'Megan Meyer', 'Male', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Margaret Sanchez', 'DC', '2001-08-21', 'Casey Brown', 'Other', 'Animal', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Melissa Barnett', 'Manga', '1963-09-01', 'Laurie Spencer', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ronald Gray', 'Image', '1962-01-26', 'Marc Wu', 'Male', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Austin Miller', 'DC', '1981-07-19', 'Kayla Hanna', 'Male', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Meghan Alexander', 'Image', '1989-07-26', 'Amanda Collins', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Micheal Sullivan', 'DC', '1996-10-30', 'Andrew Jones', 'Male', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Emily Mcconnell', 'DC', '2006-01-27', 'Dr. Sheila Garcia', 'Female', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Rodney Reeves', 'Marvel', '2009-07-16', 'Amanda Blair', 'Other', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Vincent Bennett', 'Marvel', '1995-10-22', 'Garrett Martinez', 'Male', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('William Brown', 'Image', '1977-05-17', 'Whitney Brown', 'Male', 'Animal', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Lacey Cole MD', 'Dark Horse', '2019-01-29', 'Jessica Hurley', 'Female', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Allen Cruz', 'Manga', '2011-11-28', 'Terri Clark', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Deanna Potter', 'Dark Horse', '1953-03-30', 'Robin Smith', 'Other', 'Human', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Dawn Perez', 'DC', '1985-06-30', 'Joseph Harrison', 'Female', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Craig Brooks', 'Marvel', '2004-08-07', 'Brittany Rodriguez', 'Female', 'Animal', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Ian Baker', 'DC', '2001-05-13', 'Rebecca Miles', 'Other', 'Mutant', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Allen Santiago', 'Manga', '1973-12-08', 'Adam Hayden', 'Other', 'Robot', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Emma Jimenez', 'DC', '2008-03-25', 'Austin Anderson', 'Female', 'Alien', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Harold Richardson DVM', 'DC', '1973-02-01', 'Fred Silva', 'Male', 'Human', 'Evil');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Anthony Reed', 'Dark Horse', '1979-04-24', 'Paul Evans', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('David Alexander MD', 'DC', '2005-11-10', 'Jennifer Miller', 'Female', 'Alien', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Bryan Chan', 'Dark Horse', '1993-11-11', 'Joseph Moore', 'Male', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Tony Thomas Jr.', 'DC', '1954-05-29', 'Dr. Tanya Bennett', 'Female', 'Mutant', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Shawn Williams', 'DC', '1977-02-19', 'Cheyenne Diaz', 'Female', 'Robot', 'Good');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Johnathan Perez', 'Image', '1973-08-03', 'Kara Cruz', 'Other', 'Human', 'Neutral');
INSERT INTO comics.characters (name, universe, first_appearance, creator, gender, species, alignment) VALUES ('Monique Maynard', 'Manga', '1948-03-28', 'Joshua Berry', 'Female', 'Robot', 'Evil');