version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - ./dbinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
